import type { NextPage } from 'next'
import Head from 'next/head'
import { UserCard, Navigation, AddUserCard } from '../components'
import { Container } from 'react-bootstrap'
import { useUserContext } from '../contexts'
import { useEffect, useState } from 'react'

const ROOT_URL = 'https://reqres.in'

const Home: NextPage = () => {
	const { users, setUsers } = useUserContext()
	const [number, setNumber] = useState(1)

	const fetchUsers = async () => {
		const response = await fetch(`${ROOT_URL}/api/users`)
		const data = await response.json()
		setUsers(data.data)
	}

	useEffect(() => {
		fetchUsers()
	}, [])

	return (
		<>
			<Head>
				<title>TopUp Mama</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navigation />
			<Container className='position-relative'>
				<AddUserCard />

				<UserCard />
			</Container>
		</>
	)
}

export default Home

// TODO: Register: Email, Password **✔

//TODO: Login: Email, Password, {email, minimum password length(8); a mixure of alpahnumeric and sepcial character}, show and hide password **✔

//TODO: Validation errors; aLL input should be validated **✔

//TODO: Application should have two menus **✔

//TODO: My Account: Update your account details **

//TODO: Users: The application should be able to display the logged-in user's current location **

//TODO: The applcation should include a bearer token received on login on every request being sent to the server except on login and registration *

//TODO: Assume that every token will expire after 10 minutes, the application should be able to keep track of the time left before the token expires and display it somewhere on the application *

//TODO: The application should be able to refresh the token before it expires by calling a refresh login endpoint *

//TODO: The application should be able to check the only authenticated users can access the homepage, users and my account pages *

//TODO: The application should be able to capture any error code from the server with an interceptor

//TODO: Paginate the user's page as provided from user's response from the backend *

//TODO: The payload object properties can be obtained from the URL provided
